from __future__ import annotations

from typing import Protocol

from .models import EntranceTestQuestion, LearningPathStep, PerformanceReport, ProgressSnapshot, Topic


class TopicRepository(Protocol):
    async def save_topics(self, document_id: str, topics: list[Topic]) -> None: ...
    async def list_topics(self, document_id: str, page: int, page_size: int) -> list[Topic]: ...


class AssessmentRepository(Protocol):
    async def save_entrance_test(self, student_id: str, questions: list[EntranceTestQuestion]) -> None: ...
    async def save_learning_path(self, student_id: str, steps: list[LearningPathStep]) -> None: ...
    async def save_progress(self, snapshot: ProgressSnapshot) -> None: ...
    async def save_final_report(self, report: PerformanceReport) -> None: ...


class VectorIndexPort(Protocol):
    async def upsert_document_chunks(self, document_id: str, chunks: list[str]) -> None: ...
    async def semantic_search(self, query: str, top_k: int = 5) -> list[str]: ...


class LLMPort(Protocol):
    async def generate_json(self, system_prompt: str, user_prompt: str) -> dict: ...
